### ISSUE TITLE
Can I translate your blog post? (EntityGraph)

### ISSUE THREAD

**Issue by Rebwon** [MHael22/jpa-demo#1]
Hello, I'm korean backend developer.

I was impressed by your blog post. 

Can I add a test code to the example code and publish your post in Korean on my personal blog?

my blog url : medium.com/msolo021015

**Comment by MHael22** [comment]
Hello Maeng,

Sure, feel free to improve the code by adding testing and you're allowed to publish it on your blog. But don't forget to reference it.

Thank you very much,
